/* Quay 1 Boarding Tool - single-page app.
 *
 * Three sections behind the Supabase JWT gate (auth.js): Onboard (contract
 * request + provisioning checkboxes, POST kind:'onboard_quay1'|'onboard_aqua'),
 * Provisioning status (live queue table, POST kind:'status', super-only retry
 * via kind:'retry') and Offboard (pick a person, confirm, POST kind:'offboard'
 * - backend fires the teardown +30 min, no cancel).
 *
 * All backend calls POST text/plain (no CORS preflight) to LIFECYCLE_ENDPOINT
 * with body { kind, accessToken, ...fields } - the Supabase JWT + payload at the
 * top level. The backend re-verifies the JWT + role on every write, so this
 * UI gate is convenience only. Kinds come from docs/ARCHITECTURE.md section 3
 * and are centralised in the KINDS const so they track one place.
 */
(() => {
  'use strict';

  const cfg = window.QUAY_CFG || {};
  const ENDPOINT = cfg.LIFECYCLE_ENDPOINT || '';

  // Router dispatch kinds (docs/ARCHITECTURE.md section 3, confirmed by
  // architect). Onboard splits by entity into two kinds. One place to retune.
  const KINDS = {
    onboardQuay1: 'onboard_quay1',
    onboardAqua: 'onboard_aqua',
    status: 'status',
    programs: 'programs',
    retry: 'retry',
    offboard: 'offboard',
  };

  // Provisioning systems (docs/CONTRACTS.md section 6). google/propdata/property24
  // are the core stack, checked by default. cma/dialfire are optional and
  // auto-check when the matching broker program is ticked on the Quay 1 form.
  const SYSTEMS = [
    { key: 'google',     label: 'Google Workspace', sub: 'account + groups', core: true },
    { key: 'propdata',   label: 'PropData',         sub: 'agent profile',    core: true },
    { key: 'property24', label: 'Property24',        sub: 'listing agent',    core: true },
    { key: 'cma',        label: 'CMA',               sub: 'valuation login' },
    { key: 'dialfire',   label: 'Dialfire',          sub: 'dialer seat' },
  ];

  // Broker Activities (Quay 1) - the residential clause options from the Broker Agreement
  // template. Mirrors CFG.BROKER_ACTIVITIES on the backend AND the live recruitment frontend
  // (quay-hubspot). `code` is submitted; the backend merges the matching clause into the contract
  // and derives Sale vs Rental from it (rent_* -> Rental). Commercial is parked (no template yet).
  const BROKER_ACTIVITIES = [
    { code: 'sell_res_sb', label: 'Sell · Residential · Broker (SB)' },
    { code: 'sell_res_jb', label: 'Sell · Residential · Assistant (JB)' },
    { code: 'rent_res_sb', label: 'Rent · Residential · Broker (SB)' },
    { code: 'rent_res_jb', label: 'Rent · Residential · Assistant (JB)' },
  ];

  const OFFBOARD_DELAY_MIN = 30;

  // Division directory (teams + senior brokers), loaded once from the static data file the
  // dashboards share (data/divisions.json, generated by quay-hubspot/scripts/parse_divisions.py).
  // Feeds the Quay 1 Team dropdown (grouped by section) and auto-fills the senior broker.
  let _divisions = null;         // cached ONLY on a successful, non-empty load (see below)
  let _divisionsLoading = null;  // in-flight promise so concurrent renders share one fetch
  // Fetch the division directory. A failure (or empty file) is NOT cached - it resolves to an
  // empty shape for this call but leaves _divisions null, so re-opening the form retries instead
  // of being stuck on a transient blip. Callers fall back to a free-text team field when empty.
  function loadDivisions() {
    if (_divisions) return Promise.resolve(_divisions);
    if (_divisionsLoading) return _divisionsLoading;
    _divisionsLoading = fetch('data/divisions.json', { cache: 'no-cache' })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error('divisions ' + r.status))))
      .then((d) => {
        if (d && Array.isArray(d.sections) && d.sections.length) { _divisions = d; return d; }
        return { sections: [] };                 // valid but empty - don't cache, allow retry
      })
      .catch(() => ({ sections: [] }))           // transient failure - don't cache, allow retry
      .finally(() => { _divisionsLoading = null; });
    return _divisionsLoading;
  }

  // Fill a <select> with teams grouped by division section. Each option carries that TEAM's
  // first-listed broker as the senior (data-senior / data-senior-email). Teams are de-duplicated
  // by name across sections (first wins) so the same team never appears twice.
  function fillTeamOptions(sel, divisions) {
    const secs = (divisions && divisions.sections) || [];
    if (!secs.length) { sel.innerHTML = '<option value="">No teams found</option>'; return; }
    const seen = {};
    let html = '<option value="">- select team -</option>';
    secs.forEach((sec) => {
      const opts = (sec.teams || []).map((t) => {
        const name = String(t.name || '').trim();
        if (!name || seen[name.toLowerCase()]) return '';
        seen[name.toLowerCase()] = true;
        const sb = (t.brokers && t.brokers[0]) || {};
        return `<option value="${esc(name)}" data-senior="${esc(sb.name || '')}"`
          + ` data-senior-email="${esc(sb.email || '')}">${esc(name)}</option>`;
      }).filter(Boolean).join('');
      if (opts) html += `<optgroup label="${esc(sec.name || 'Teams')}">${opts}</optgroup>`;
    });
    sel.innerHTML = html;
  }

  // Availability fallback: when divisions.json is unreachable or empty, swap the Team <select>
  // (whose only option would be a blank placeholder, making a required field unsubmittable) for a
  // free-text <input> of the same name, so a broker onboarding can still be created by typing the
  // team. Senior fields then stay manually editable (no auto-fill source without the directory).
  function degradeTeamToText(sel) {
    if (!sel || !sel.parentNode) return;
    const req = sel.hasAttribute('aria-required');
    const input = document.createElement('input');
    input.id = sel.id; input.name = sel.name; input.type = 'text'; input.autocomplete = 'off';
    input.placeholder = 'Type the team name';
    if (req) input.setAttribute('aria-required', 'true');
    sel.replaceWith(input);
  }

  // ── DOM helpers ───────────────────────────────────────────────────────────
  const $ = (sel, root = document) => root.querySelector(sel);
  const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  function el(html) { const t = document.createElement('template'); t.innerHTML = html.trim(); return t.content.firstElementChild; }

  let USER = null;              // logged-in staff (from AUTH.getSession)
  let statusCache = [];         // last provisioning-status rows (feeds offboard picker)

  // ── Toast ─────────────────────────────────────────────────────────────────
  function toast(title, body, kind) {
    const host = $('#toastHost');
    const node = el(`<div class="toast ${kind || ''}" role="status">
      <strong>${esc(title)}</strong>${body ? esc(body) : ''}</div>`);
    host.appendChild(node);
    setTimeout(() => { node.style.opacity = '0'; setTimeout(() => node.remove(), 250); }, 5200);
  }

  // ── API ───────────────────────────────────────────────────────────────────
  // POST text/plain so no CORS preflight fires. Body is { kind, accessToken,
  // ...fields } (docs/CONTRACTS.md section 7): the Supabase JWT rides as
  // `accessToken` and the payload fields sit at the top level alongside kind.
  async function api(kind, data) {
    if (!ENDPOINT) throw new Error('LIFECYCLE_ENDPOINT not set in config.js');
    const accessToken = await window.AUTH.getAccessToken();
    if (!accessToken) throw new Error('Session expired, sign in again.');
    const res = await fetch(ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'text/plain;charset=utf-8' },
      body: JSON.stringify(Object.assign({ kind, accessToken }, data || {})),
    });
    let json;
    try { json = await res.json(); } catch (_) { throw new Error('Bad response from server.'); }
    if (!res.ok || json.ok === false) throw new Error(json && json.error ? json.error : 'Request failed.');
    return json;
  }

  // Shared surface for split view modules. The Offboard view lives in its own
  // file (app.offboard.js) to keep this file under the 500-line cap; it reaches
  // the shared helpers + mutable state through here. No behaviour change - the
  // getters/setters read and write the same closure variables as before.
  const HUB = (window.HUB = window.HUB || {});
  HUB.$ = $; HUB.esc = esc; HUB.el = el; HUB.api = api; HUB.toast = toast;
  HUB.KINDS = KINDS; HUB.OFFBOARD_DELAY_MIN = OFFBOARD_DELAY_MIN;
  HUB.getUser = () => USER;
  HUB.getStatusCache = () => statusCache;
  HUB.setStatusCache = (v) => { statusCache = v; };

  //  ROUTER
  const VIEWS = {
    onboard: viewOnboard, provisioning: viewProvisioning, programs: viewPrograms,
    offboard: (root) => window.HUB.viewOffboard(root),  // defined in app.offboard.js
  };

  function route(tab) {
    // Brokers cannot open Offboard; bounce them to Onboard.
    if (tab === 'offboard' && !(USER && USER.canOffboard)) tab = 'onboard';
    document.querySelectorAll('.tab-btn').forEach((b) => {
      const on = b.dataset.tab === tab;
      b.classList.toggle('active', on);
      if (on) b.setAttribute('aria-current', 'page'); else b.removeAttribute('aria-current');
    });
    const main = $('#content');
    main.innerHTML = '';
    (VIEWS[tab] || viewOnboard)(main);
    main.focus({ preventScroll: true });
  }

  //  1. ONBOARD
  function viewOnboard(root) {
    let entity = 'quay1';

    const wrap = el(`<div class="stack">
      <div class="section-head">
        <h2>Onboard a new person</h2>
        <p>Generate the contract and record the systems to provision. Accounts are created in the weekly Wednesday 08:00 batch, once the signed contract and FICA documents are in. Choose the entity, then complete the details. Fields marked with a red asterisk are required.</p>
      </div>
      <div class="card card-pad stack">
        <div class="seg" role="tablist" aria-label="Entity">
          <button type="button" role="tab" data-ent="quay1" class="active" aria-selected="true">Quay 1</button>
          <button type="button" role="tab" data-ent="aqua" aria-selected="false">Aqua Promotions</button>
        </div>
        <form id="onboardForm" novalidate></form>
      </div>
    </div>`);

    const form = $('#onboardForm', wrap);
    const seg = $('.seg', wrap);
    seg.addEventListener('click', (e) => {
      const b = e.target.closest('button[data-ent]'); if (!b) return;
      entity = b.dataset.ent;
      seg.querySelectorAll('button').forEach((x) => {
        const on = x === b; x.classList.toggle('active', on); x.setAttribute('aria-selected', String(on));
      });
      renderForm();
    });

    function fieldText(name, label, opts = {}) {
      const req = opts.required ? ' <span class="req" aria-hidden="true">*</span>' : '';
      const type = opts.type || 'text';
      const cls = opts.full ? 'field full' : 'field';
      const hint = opts.hint ? `<span class="hint">${esc(opts.hint)}</span>` : '';
      const ro = opts.readonly ? ' readonly' : '';
      const ph = opts.placeholder ? ` placeholder="${esc(opts.placeholder)}"` : '';
      return `<div class="${cls}">
        <label for="f_${name}">${esc(label)}${req}</label>
        <input id="f_${name}" name="${name}" type="${type}"${ro}${ph} ${opts.required ? 'aria-required="true"' : ''} autocomplete="off">
        ${hint}<span class="field-err" id="e_${name}" aria-live="polite"></span></div>`;
    }
    function fieldSelect(name, label, options, req) {
      const opts = options.map((o) => `<option value="${esc(o.v)}">${esc(o.t)}</option>`).join('');
      return `<div class="field">
        <label for="f_${name}">${esc(label)}${req ? ' <span class="req" aria-hidden="true">*</span>' : ''}</label>
        <select id="f_${name}" name="${name}" ${req ? 'aria-required="true"' : ''}>${opts}</select>
        <span class="field-err" id="e_${name}"></span></div>`;
    }
    // Team dropdown, grouped by division section. Each option carries the section's first-listed
    // broker as its senior (data-senior / data-senior-email) so the Senior fields auto-fill on
    // change. Options are injected after render once divisions.json has loaded (fillTeamOptions).
    function teamField(name, label, req) {
      return `<div class="field">
        <label for="f_${name}">${esc(label)}${req ? ' <span class="req" aria-hidden="true">*</span>' : ''}</label>
        <select id="f_${name}" name="${name}" ${req ? 'aria-required="true"' : ''}>
          <option value="">Loading teams…</option></select>
        <span class="field-err" id="e_${name}"></span></div>`;
    }

    function renderForm() {
      const common =
        fieldText('name', 'Full name', { required: true }) +
        fieldText('id_number', 'ID number', { required: true }) +
        fieldText('contact', 'Cell number', { required: true, type: 'tel' }) +
        fieldText('email', 'Personal email', { required: true, type: 'email', hint: 'Used to send the contract + induction pack.' }) +
        fieldText('start_date', 'Start date', { required: true, type: 'date' }) +
        fieldText('division', 'Division', {});

      const quay1 =
        // Broker activity drives BOTH the {{BROKER_ACTIVITY}} clause and the Sale-vs-Rental
        // template (rent_* -> Rental), so a separate deal_type field is no longer needed.
        fieldSelect('activity', 'Broker activities',
          [{ v: '', t: '- select activity -' }].concat(BROKER_ACTIVITIES.map((a) => ({ v: a.code, t: a.label }))),
          true) +
        teamField('team', 'Team', true) +
        fieldText('senior_name', 'Reporting senior (name)', { placeholder: 'auto-fills from team - editable' }) +
        fieldText('senior_email', 'Reporting senior (email)', { type: 'email' }) +
        fieldText('commission', 'Commission %', { required: true, hint: 'e.g. 50 / 60 / 70' });

      const aqua =
        fieldSelect('agreement_type', 'Agreement type', [
          { v: 'monthly', t: 'Monthly' }, { v: 'fixed', t: 'Fixed term' }, { v: 'permanent', t: 'Permanent' },
        ], true) +
        fieldText('designation', 'Role / designation', { required: true }) +
        // end_date is required for a fixed-term MOA; shown only when agreement_type=fixed.
        `<div class="field" id="endDateWrap" hidden>
          <label for="f_end_date">End date <span class="req" aria-hidden="true">*</span></label>
          <input id="f_end_date" name="end_date" type="date">
          <span class="field-err" id="e_end_date" aria-live="polite"></span></div>` +
        fieldText('work_hours', 'Work hours', { hint: 'e.g. Mon to Fri, 08:00 to 17:00' }) +
        fieldText('remuneration', 'Remuneration', { hint: 'Monthly package or rate.' });

      // Provisioning systems: core three checked by default; cma/dialfire off (tick as needed).
      const systems = SYSTEMS.map((s) => `<label class="check">
        <input type="checkbox" name="sys_${s.key}" value="${s.key}" ${s.core ? 'checked' : ''}>
        <span><span class="ck-label">${esc(s.label)}</span><span class="ck-sub">${esc(s.sub)}</span></span>
      </label>`).join('');

      const canOnboard = USER && USER.canOnboard;
      const brokerOnly = USER && USER.isBroker && !USER.isSuper && !USER.isAdmin;
      const gate = !canOnboard
        ? `<div class="notice warn">You do not have permission to submit an onboarding request.</div>`
        : brokerOnly
          ? `<div class="notice">You are submitting as ${esc(USER.name || 'yourself')}. The request is logged under your name; a super or admin oversees account provisioning.</div>`
          : '';

      const roleTitle = entity === 'aqua' ? 'Agreement' : 'Role and contract';
      form.innerHTML = `
        <div class="form-section">
          <h3 class="fs-title">Person</h3>
          <div class="form-grid">${common}</div>
        </div>
        <div class="form-section">
          <h3 class="fs-title">${roleTitle}</h3>
          <div class="form-grid">${entity === 'aqua' ? aqua : quay1}</div>
        </div>
        <div class="form-section">
          <h3 class="fs-title">Provisioning</h3>
          <fieldset>
            <legend>Provision these systems</legend>
            <div class="check-grid">${systems}</div>
          </fieldset>
        </div>
        ${gate}
        <div class="form-actions">
          <button type="submit" class="btn btn-primary" id="obSubmit" ${canOnboard ? '' : 'disabled'}>Create contract</button>
          <button type="reset" class="btn btn-ghost">Clear</button>
        </div>`;

      // Toggle the is-on styling on every check card.
      form.querySelectorAll('.check input').forEach((i) => {
        const sync = () => i.closest('.check').classList.toggle('is-on', i.checked);
        sync(); i.addEventListener('change', sync);
      });
      // Quay 1: populate the Team dropdown from divisions.json and auto-fill the senior broker.
      // Both senior fields are editable and auto-fill on team change WITHOUT clobbering a manual
      // edit. If the directory can't load (or is empty), the Team select degrades to a free-text
      // input so onboarding is never blocked by a missing/lagging data file.
      const teamSel = form.querySelector('select[name="team"]');
      if (teamSel && entity !== 'aqua') {
        const seniorName = $('#f_senior_name', form), seniorEmail = $('#f_senior_email', form);
        // Clear the auto-fill flag as soon as the user types their own value.
        seniorName && seniorName.addEventListener('input', () => { seniorName.dataset.auto = ''; });
        seniorEmail && seniorEmail.addEventListener('input', () => { seniorEmail.dataset.auto = ''; });
        const autoFill = (field, val) => {
          if (field && (!field.value || field.dataset.auto === '1')) { field.value = val; field.dataset.auto = '1'; }
        };
        loadDivisions().then((d) => {
          if (!form.isConnected) return;               // view switched away while loading
          if (!d.sections || !d.sections.length) { degradeTeamToText(teamSel); return; }
          fillTeamOptions(teamSel, d);
          teamSel.addEventListener('change', () => {
            const opt = teamSel.selectedOptions[0];
            autoFill(seniorName, (opt && opt.dataset.senior) || '');
            autoFill(seniorEmail, (opt && opt.dataset.seniorEmail) || '');
          });
        });
      }
      // Aqua fixed-term reveals the required end_date field.
      const agr = form.querySelector('select[name="agreement_type"]');
      if (agr) {
        const endWrap = $('#endDateWrap', form), endInput = $('#f_end_date', form);
        const syncEnd = () => {
          const fixed = agr.value === 'fixed';
          if (endWrap) endWrap.hidden = !fixed;
          if (endInput) {
            if (fixed) { endInput.setAttribute('aria-required', 'true'); }
            else { endInput.removeAttribute('aria-required'); endInput.removeAttribute('aria-invalid'); }
          }
        };
        syncEnd(); agr.addEventListener('change', syncEnd);
      }
    }

    form.addEventListener('submit', (e) => { e.preventDefault(); submitOnboard(form, entity); });
    renderForm();
    root.appendChild(wrap);
  }

  function collect(form) {
    const out = {};
    form.querySelectorAll('input, select').forEach((i) => {
      if (i.type === 'checkbox') return;
      out[i.name] = i.value.trim();
    });
    return out;
  }

  function validateOnboard(form) {
    let firstBad = null;
    form.querySelectorAll('[aria-required="true"]').forEach((i) => {
      const errEl = $('#e_' + i.name, form);
      const bad = !i.value.trim();
      i.setAttribute('aria-invalid', bad ? 'true' : 'false');
      if (errEl) errEl.textContent = bad ? 'Required.' : '';
      if (bad && !firstBad) firstBad = i;
    });
    if (firstBad) firstBad.focus();
    return !firstBad;
  }

  async function submitOnboard(form, entity) {
    if (!validateOnboard(form)) { toast('Check the form', 'Some required fields are missing.', 'err'); return; }
    const data = collect(form);
    data.entity = entity;
    // Backend reads the provisioning selection under `systems` (CONTRACTS section 6).
    data.systems = SYSTEMS.map((s) => s.key).filter((k) => form.querySelector(`input[name="sys_${k}"]`).checked);
    data.requester_name = USER ? USER.name : '';
    data.requester_email = USER ? USER.email : '';

    const btn = $('#obSubmit', form);
    btn.classList.add('loading'); btn.disabled = true;
    try {
      const kind = entity === 'aqua' ? KINDS.onboardAqua : KINDS.onboardQuay1;
      const r = await api(kind, data);
      toast('Onboarding submitted', `Contract sent to ${data.name}. Accounts are created in the Wednesday 08:00 batch once their signed contract + FICA docs are in (${data.systems.length} system(s) queued).`, 'ok');
      form.reset();
      // Restore check defaults: core systems on, optional systems off.
      form.querySelectorAll('.check input').forEach((i) => {
        const sys = SYSTEMS.find((s) => i.name === `sys_${s.key}`);
        i.checked = !!(sys && sys.core);
        i.closest('.check').classList.toggle('is-on', i.checked);
      });
      form.querySelectorAll('[aria-invalid]').forEach((i) => i.removeAttribute('aria-invalid'));
      if (r && r.folderId) statusCache = [];  // force a refresh next time status opens
    } catch (err) {
      toast('Could not submit', err.message, 'err');
    } finally {
      btn.classList.remove('loading'); btn.disabled = false;
    }
  }

  //  PROGRAMS - who on a team holds CMA + PropData accounts (role-scoped by the backend)
  function viewPrograms(root) {
    const wrap = el(`<div class="stack">
      <div class="section-head">
        <h2>Programs</h2>
        <p>CMA and PropData accounts per team, grouped by senior broker. A senior sees their own team; supers and admins see everyone.</p>
      </div>
      <div class="card card-pad">
        <div class="toolbar">
          <div class="muted" id="progMeta">Loading...</div>
          <div class="toolbar-right">
            <button type="button" class="btn btn-ghost btn-sm" id="progRefresh">Refresh</button>
          </div>
        </div>
        <div class="prog-legend">
          <span class="prog-chip ok">CMA</span> has a CMA account
          <span class="prog-chip pd">Agent</span> full PropData agent
          <span class="prog-chip pd">Spec #</span> property-specialist profile
          <span class="prog-chip off">dimmed</span> inactive
          <span class="prog-chip none">–</span> none
        </div>
        <div id="progBody"></div>
      </div>
    </div>`);
    root.appendChild(wrap);
    $('#progRefresh', wrap).addEventListener('click', () => loadPrograms(wrap, true));
    loadPrograms(wrap, false);
  }

  let programsCache = null;
  async function loadPrograms(wrap, force) {
    const body = $('#progBody', wrap), meta = $('#progMeta', wrap);
    body.innerHTML = `<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>`;
    meta.textContent = 'Loading...';
    // The first POST to a cold Apps Script /exec occasionally returns a non-JSON body
    // ("Bad response from server"); it always succeeds on a retry. So retry twice, briefly,
    // before surfacing an error - the user should not have to hit Refresh.
    try {
      if (programsCache && !force) { renderPrograms(body, meta, programsCache); return; }
      let r, lastErr;
      for (let attempt = 0; attempt < 3; attempt++) {
        try { r = await api(KINDS.programs, {}); lastErr = null; break; }
        catch (e) { lastErr = e; await new Promise((res) => setTimeout(res, 600)); }
      }
      if (lastErr) throw lastErr;
      programsCache = r;
      renderPrograms(body, meta, r);
    } catch (err) {
      meta.textContent = '';
      body.innerHTML = `<div class="state"><div class="state-title">Could not load Programs</div><div>${esc(err.message)}</div></div>`;
    }
  }

  const SCOPE_LABEL = { all: 'all teams', senior: 'your team', self: 'your account' };
  function renderPrograms(body, meta, r) {
    const sections = (r && r.sections) || [];
    const teamCount = sections.reduce((n, s) => n + (s.teams ? s.teams.length : 0), 0);
    meta.textContent = sections.length
      ? `Showing ${SCOPE_LABEL[r.scope] || ''} · ${teamCount} team(s)`
      : '';
    if (!sections.length) {
      body.innerHTML = `<div class="state"><div class="state-title">Nothing to show</div><div>No team accounts are visible for your login yet.</div></div>`;
      return;
    }
    const pdChip = (pd) => {
      if (!pd) return `<span class="prog-chip none">–</span>`;
      const lbl = pd.type === 'agent' ? 'Agent' : `Spec #${esc(pd.number)}`;
      const cls = pd.active ? 'pd' : 'off';
      return `<span class="prog-chip ${cls}">${lbl}</span>` + (pd.active ? '' : `<span class="prog-chip none">inactive</span>`);
    };
    const rowHtml = (p) => `<div class="prog-tr${p.senior ? ' sr' : ''}">
        <span class="prog-nm">${p.senior ? '<span class="prog-star">★</span>' : '<span class="prog-star dim">·</span>'}${esc(p.name)}${p.senior ? ' <em>SENIOR</em>' : ''}</span>
        <span>${p.cma ? '<span class="prog-chip ok">✓</span>' : '<span class="prog-chip none">–</span>'}</span>
        <span>${pdChip(p.pd)}</span>
      </div>`;
    const teamHtml = (t) => {
      const n = t.people.length;
      const nc = t.people.filter((p) => p.cma).length;
      const np = t.people.filter((p) => p.pd).length;
      const head = t.name
        ? `<div class="prog-teamh"><div class="prog-tname">${esc(t.name)}${t.senior ? `<span class="prog-tsr">Senior: ${esc(t.senior)}</span>` : ''}</div>
             <div class="prog-tcount">CMA ${nc}/${n} · PropData ${np}/${n}</div></div>`
        : '';
      return `<div class="prog-card">${head}
        <div class="prog-tbl"><div class="prog-th"><span>Broker</span><span>CMA</span><span>PropData</span></div>
        ${t.people.map(rowHtml).join('')}</div></div>`;
    };
    body.innerHTML = sections.map((s) =>
      `<div class="prog-sech">${esc(s.name)}</div>${s.teams.map(teamHtml).join('')}`).join('');
  }

  //  2. PROVISIONING STATUS
  function viewProvisioning(root) {
    const wrap = el(`<div class="stack">
      <div class="section-head">
        <h2>Provisioning status</h2>
        <p>Live view of the account-provisioning queue: one row per person and system. Google and PropData run inside Apps Script; Property24, CMA and Dialfire run on the worker.</p>
      </div>
      <div class="card card-pad">
        <div class="toolbar">
          <div class="muted" id="provMeta">Loading...</div>
          <div class="toolbar-right">
            <button type="button" class="btn btn-ghost btn-sm" id="provRefresh">Refresh</button>
          </div>
        </div>
        <div id="provBody"></div>
      </div>
    </div>`);
    root.appendChild(wrap);
    $('#provRefresh', wrap).addEventListener('click', () => loadStatus(wrap, true));
    loadStatus(wrap, false);
  }

  const STATUS_CLASS = {
    pending: 's-pending', in_progress: 's-inprogress', inprogress: 's-inprogress',
    done: 's-done', error: 's-error', skipped: 's-skipped',
  };
  const STATUS_LABEL = {
    pending: 'Pending', in_progress: 'In progress', inprogress: 'In progress',
    done: 'Done', error: 'Error', skipped: 'Skipped',
  };

  async function loadStatus(wrap, force) {
    const body = $('#provBody', wrap), meta = $('#provMeta', wrap);
    body.innerHTML = `<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>`;
    meta.textContent = 'Loading...';
    try {
      const r = (statusCache.length && !force) ? { rows: statusCache } : await api(KINDS.status, {});
      // CONTRACTS 8.3: provisioning rows live under `rows`; `offboarding` is
      // separate admin-only context we don't render here.
      const rows = (r.rows || r.data || []).slice();
      statusCache = rows;
      renderStatus(body, meta, rows);
    } catch (err) {
      meta.textContent = '';
      body.innerHTML = `<div class="state"><div class="state-title">Could not load the queue</div><div>${esc(err.message)}</div></div>`;
    }
  }

  function renderStatus(body, meta, rows) {
    if (!rows.length) {
      meta.textContent = '';
      body.innerHTML = `<div class="state"><div class="state-title">Nothing in the queue</div><div>Provisioning rows appear here once an onboarding request is submitted.</div></div>`;
      return;
    }
    const canRetry = USER && USER.isSuper;
    meta.textContent = `${rows.length} queue row(s)`;
    const head = `<thead><tr>
      <th>Person</th><th>Entity</th><th>System</th><th>Action</th><th>Status</th><th>Detail</th>
      ${canRetry ? '<th aria-label="Retry"></th>' : ''}</tr></thead>`;
    const trs = rows.map((row) => {
      const st = String(row.status || 'pending').toLowerCase().replace(/\s+/g, '_');
      const cls = STATUS_CLASS[st] || 's-pending';
      const lbl = STATUS_LABEL[st] || row.status || 'Pending';
      const ent = (row.entity || '').toLowerCase();
      const entTag = ent === 'aqua' ? '<span class="entity-tag aqua">Aqua</span>'
        : ent === 'quay1' ? '<span class="entity-tag quay1">Quay 1</span>' : '<span class="muted">-</span>';
      const detail = row.result_json && typeof row.result_json === 'object'
        ? (row.result_json.username || row.result_json.id || row.result_json.error || '')
        : (row.result_json || row.detail || '');
      const retryCell = canRetry
        ? `<td class="actions">${(st === 'error') ? `<button type="button" class="btn btn-ghost btn-sm" data-retry="${esc(row.queue_id || '')}">Retry</button>` : ''}</td>`
        : '';
      return `<tr>
        <td class="who">${esc(row.full_name || row.name || '')}</td>
        <td>${entTag}</td>
        <td class="sys">${esc(row.system || '')}</td>
        <td class="sys">${esc(row.action || 'create')}</td>
        <td><span class="pill ${cls}">${esc(lbl)}</span></td>
        <td class="muted">${esc(detail).slice(0, 80)}</td>
        ${retryCell}</tr>`;
    }).join('');
    body.innerHTML = `<div class="tbl-wrap"><table class="tbl">${head}<tbody>${trs}</tbody></table></div>`;

    if (canRetry) {
      body.querySelectorAll('[data-retry]').forEach((b) => {
        b.addEventListener('click', async () => {
          b.classList.add('loading'); b.disabled = true;
          try {
            await api(KINDS.retry, { queue_id: b.dataset.retry });
            toast('Retry queued', 'The worker will pick this row up again.', 'ok');
            statusCache = [];
            loadStatus(body.closest('.stack'), true);
          } catch (err) {
            toast('Retry failed', err.message, 'err');
            b.classList.remove('loading'); b.disabled = false;
          }
        });
      });
    }
  }

  //  AUTH BOOT (login gate + session)
  function initLoginGate() {
    const gate = $('#loginGate'), userInput = $('#loginUser'), dots = $('#pinDots'),
          errEl = $('#loginError'), pad = $('#loginKeypad');
    let pin = '';
    const paint = () => dots.querySelectorAll('.pin-dot').forEach((d, i) => d.classList.toggle('filled', i < pin.length));
    const showErr = (m) => { errEl.textContent = m; errEl.hidden = false; gate.classList.add('pin-error'); setTimeout(() => gate.classList.remove('pin-error'), 500); };

    async function attempt() {
      const u = userInput.value.trim();
      if (!u) { showErr('Enter your username.'); return; }
      errEl.hidden = true;
      const r = await window.AUTH.signIn(u, pin);
      pin = ''; paint();
      if (!r.ok) { showErr(r.error || 'Sign-in failed.'); return; }
      USER = r.user; onSignedIn();
    }
    pad.addEventListener('click', (e) => {
      const b = e.target.closest('button'); if (!b) return;
      if (b.hasAttribute('data-clear')) { pin = ''; paint(); return; }
      if (b.hasAttribute('data-back')) { pin = pin.slice(0, -1); paint(); return; }
      if (b.dataset.d && pin.length < 6) { pin += b.dataset.d; paint(); if (pin.length === 6) attempt(); }
    });
    document.addEventListener('keydown', (e) => {
      if (document.body.classList.contains('pre-auth') === false) return;
      if (e.key >= '0' && e.key <= '9' && pin.length < 6) { pin += e.key; paint(); if (pin.length === 6) attempt(); }
      else if (e.key === 'Backspace' && document.activeElement !== userInput) { pin = pin.slice(0, -1); paint(); }
      else if (e.key === 'Enter' && pin.length === 6) attempt();
    });
  }

  function onSignedIn() {
    document.body.classList.remove('pre-auth');
    const gate = $('#loginGate'); if (gate) gate.remove();  // uncover the app shell
    // Shared cross-app switcher on the Quay 1 flag (superusers only; no-op else).
    if (window.QuayNav) window.QuayNav.mount({ isSuper: !!(USER && USER.isSuper), current: 'boarding' });
    const so = $('#signOutBtn'); so.hidden = false;
    $('#signOutWho').textContent = USER && USER.name ? USER.name + ' - ' : '';
    so.addEventListener('click', async () => { await window.AUTH.signOut(); location.reload(); }, { once: true });
    // Offboarding is super/admin only; a broker never sees the tab (the backend
    // also rejects a broker 'offboard' POST, so this is convenience, not the gate).
    if (!(USER && USER.canOffboard)) {
      const offBtn = document.querySelector('.tab-btn[data-tab="offboard"]');
      if (offBtn) offBtn.remove();
    }
    document.querySelectorAll('.tab-btn').forEach((b) => b.addEventListener('click', () => route(b.dataset.tab)));
    route('onboard');
  }

  async function boot() {
    document.body.classList.add('pre-auth');
    initLoginGate();
    try {
      const u = await window.AUTH.getSession();
      if (u) { USER = u; onSignedIn(); }
    } catch (_) { /* stay on the gate */ }
  }

  document.addEventListener('DOMContentLoaded', boot);
})();
